-- SynkTime Database Schema for MariaDB
-- This schema defines all tables with correct case-sensitive naming for MariaDB compatibility

-- Companies table
CREATE TABLE IF NOT EXISTS EMPRESA (
    ID_EMPRESA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    DIRECCION TEXT,
    TELEFONO VARCHAR(50),
    EMAIL VARCHAR(255),
    ACTIVO ENUM('S', 'N') DEFAULT 'S',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Sede (Locations) table
CREATE TABLE IF NOT EXISTS SEDE (
    ID_SEDE INT AUTO_INCREMENT PRIMARY KEY,
    ID_EMPRESA INT NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    DIRECCION TEXT,
    TELEFONO VARCHAR(50),
    ACTIVO ENUM('S', 'N') DEFAULT 'S',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA)
);

-- Establishments table
CREATE TABLE IF NOT EXISTS ESTABLECIMIENTO (
    ID_ESTABLECIMIENTO INT AUTO_INCREMENT PRIMARY KEY,
    ID_SEDE INT NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    DIRECCION TEXT,
    TELEFONO VARCHAR(50),
    ACTIVO ENUM('S', 'N') DEFAULT 'S',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_SEDE) REFERENCES SEDE(ID_SEDE)
);

-- Roles table
CREATE TABLE IF NOT EXISTS ROL (
    ID_ROL INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,
    ACTIVO ENUM('S', 'N') DEFAULT 'S',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Users table
CREATE TABLE IF NOT EXISTS USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(100) UNIQUE NOT NULL,
    CONTRASENA VARCHAR(255) NOT NULL,
    NOMBRE_COMPLETO VARCHAR(255),
    EMAIL VARCHAR(255),
    ROL ENUM('ADMINISTRADOR', 'GERENTE', 'ASISTENCIA', 'DUEÑO', 'DUENO') DEFAULT 'ASISTENCIA',
    ID_EMPRESA INT NOT NULL,
    ACTIVO ENUM('S', 'N') DEFAULT 'S',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA)
);

-- Employees table  
CREATE TABLE IF NOT EXISTS EMPLEADO (
    ID_EMPLEADO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    APELLIDO VARCHAR(255) NOT NULL,
    DNI VARCHAR(50) UNIQUE,
    EMAIL VARCHAR(255),
    TELEFONO VARCHAR(50),
    ID_ESTABLECIMIENTO INT NOT NULL,
    ESTADO ENUM('A', 'I') DEFAULT 'A',
    ACTIVO ENUM('S', 'N') DEFAULT 'S',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_ESTABLECIMIENTO) REFERENCES ESTABLECIMIENTO(ID_ESTABLECIMIENTO)
);

-- Employee schedules table
CREATE TABLE IF NOT EXISTS EMPLEADO_HORARIO (
    ID_EMPLEADO_HORARIO INT AUTO_INCREMENT PRIMARY KEY,
    ID_EMPLEADO INT NOT NULL,
    DIA_SEMANA ENUM('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO') NOT NULL,
    HORA_ENTRADA TIME NOT NULL,
    HORA_SALIDA TIME NOT NULL,
    ACTIVO ENUM('S', 'N') DEFAULT 'S',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO),
    UNIQUE KEY unique_employee_day (ID_EMPLEADO, DIA_SEMANA)
);

-- Attendance table
CREATE TABLE IF NOT EXISTS ASISTENCIAS (
    ID_ASISTENCIA INT AUTO_INCREMENT PRIMARY KEY,
    ID_EMPLEADO INT NOT NULL,
    FECHA DATE NOT NULL,
    HORA_ENTRADA TIME,
    HORA_SALIDA TIME,
    OBSERVACIONES TEXT,
    FOTO_ENTRADA VARCHAR(255),
    FOTO_SALIDA VARCHAR(255),
    VERIFICACION_ENTRADA ENUM('fingerprint', 'facial', 'traditional') DEFAULT 'traditional',
    VERIFICACION_SALIDA ENUM('fingerprint', 'facial', 'traditional') DEFAULT 'traditional',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO),
    UNIQUE KEY unique_employee_date (ID_EMPLEADO, FECHA)
);

-- Biometric data table
CREATE TABLE IF NOT EXISTS biometric_data (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_EMPLEADO INT NOT NULL,
    BIOMETRIC_TYPE ENUM('fingerprint', 'facial') NOT NULL,
    FINGER_TYPE VARCHAR(20),
    BIOMETRIC_DATA LONGTEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ACTIVO TINYINT(1) DEFAULT 1,
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO),
    UNIQUE KEY unique_employee_finger (ID_EMPLEADO, FINGER_TYPE)
);

-- Biometric logs table
CREATE TABLE IF NOT EXISTS biometric_logs (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_EMPLEADO INT NOT NULL,
    VERIFICATION_METHOD ENUM('fingerprint', 'facial', 'traditional') NOT NULL,
    VERIFICATION_SUCCESS TINYINT(1) DEFAULT 0,
    FECHA DATE,
    HORA TIME,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
);

-- Civic holidays table
CREATE TABLE IF NOT EXISTS DIAS_CIVICOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FECHA DATE NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    TIPO ENUM('FIJO', 'VARIABLE') DEFAULT 'FIJO',
    ACTIVO TINYINT(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY unique_date (FECHA)
);

-- Holidays cache table
CREATE TABLE IF NOT EXISTS HOLIDAYS_CACHE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    YEAR INT NOT NULL,
    HOLIDAY_DATA LONGTEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_year (YEAR)
);

-- Activity logs table
CREATE TABLE IF NOT EXISTS LOG (
    ID_LOG INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT,
    ACCION VARCHAR(255),
    DETALLE TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

-- Insert default company data
INSERT IGNORE INTO EMPRESA (ID_EMPRESA, NOMBRE, ACTIVO) VALUES 
(1, 'SynkTime Company', 'S');

-- Insert default sede
INSERT IGNORE INTO SEDE (ID_SEDE, ID_EMPRESA, NOMBRE, ACTIVO) VALUES 
(1, 1, 'Sede Principal', 'S');

-- Insert default establecimiento  
INSERT IGNORE INTO ESTABLECIMIENTO (ID_ESTABLECIMIENTO, ID_SEDE, NOMBRE, ACTIVO) VALUES 
(1, 1, 'Establecimiento Principal', 'S');

-- Insert default admin user (password: admin123)
INSERT IGNORE INTO USUARIO (ID_USUARIO, USERNAME, CONTRASENA, NOMBRE_COMPLETO, ROL, ID_EMPRESA, ACTIVO) VALUES 
(1, 'admin', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Administrador del Sistema', 'ADMINISTRADOR', 1, 'S');

-- Insert sample employee
INSERT IGNORE INTO EMPLEADO (ID_EMPLEADO, NOMBRE, APELLIDO, DNI, ID_ESTABLECIMIENTO, ESTADO, ACTIVO) VALUES 
(1, 'Juan', 'Pérez', '12345678', 1, 'A', 'S');