-- Migration to add biometric fields to EMPLEADO table
-- For SynkTime biometric enrollment functionality

-- Add columns for biometric data
ALTER TABLE EMPLEADO 
ADD COLUMN FACIAL_RECOGNITION_ENABLED ENUM('Y', 'N') DEFAULT 'N' AFTER ACTIVO,
ADD COLUMN FACIAL_DATA LONGTEXT NULL AFTER FACIAL_RECOGNITION_ENABLED,
ADD COLUMN FINGERPRINT_ENABLED ENUM('Y', 'N') DEFAULT 'N' AFTER FACIAL_DATA,
ADD COLUMN FINGERPRINT_DATA LONGTEXT NULL AFTER FINGERPRINT_ENABLED,
ADD COLUMN BIOMETRIC_UPDATED_AT TIMESTAMP NULL DEFAULT NULL AFTER FINGERPRINT_DATA,
ADD COLUMN BIOMETRIC_UPDATED_BY INT NULL AFTER BIOMETRIC_UPDATED_AT;

-- Create biometric log table for audit trail
CREATE TABLE IF NOT EXISTS BIOMETRIC_LOG (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_EMPLEADO INT NOT NULL,
    TYPE ENUM('FACIAL', 'FINGERPRINT') NOT NULL,
    ACTION ENUM('ENROLLED', 'UPDATED', 'DELETED', 'VERIFIED') NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY INT NULL,
    INDEX idx_biometric_log_employee (ID_EMPLEADO),
    INDEX idx_biometric_log_type (TYPE),
    INDEX idx_biometric_log_date (CREATED_AT)
);

-- Create index for faster biometric lookups
CREATE INDEX idx_empleado_facial ON EMPLEADO(FACIAL_RECOGNITION_ENABLED);
CREATE INDEX idx_empleado_fingerprint ON EMPLEADO(FINGERPRINT_ENABLED);

-- Update employees 1, 2, 3 to have facial recognition enabled by default
UPDATE EMPLEADO 
SET FACIAL_RECOGNITION_ENABLED = 'Y' 
WHERE ID_EMPLEADO IN (1, 2, 3);